import type { Job } from "./types";

export const JOBS: Job[] = [
  {
    id: 1,
    title: "Junior Accountant",
    company: "Local Logistics Pvt. Ltd.",
    city: "Kathmandu",
    salaryMin: 25000,
    salaryMax: 35000,
    type: "entry",
    verified: true,
    tags: ["Accounting", "Excel", "Tally"],
    exp: 0,
    teaser: "Assist with bookkeeping, invoices, and reconciliations.",
    description:
      "Maintain ledgers, prepare invoices, reconcile statements, coordinate with vendors. Basic Tally/Excel skills required.",
    applyUrl: "#",
  },
  {
    id: 2,
    title: "Administrative Assistant",
    company: "Municipality Office",
    city: "Bhaktapur",
    salaryMin: 0,
    salaryMax: 0,
    type: "entry",
    verified: true,
    tags: ["Clerical", "Government"],
    exp: 1,
    teaser: "Clerical role supporting municipal operations.",
    description:
      "Filing, scheduling, citizen support. Government pay scale Level 4. Knowledge of Nepali official formats preferred.",
    applyUrl: "#",
  },
  {
    id: 3,
    title: "Field Officer",
    company: "HopeForAll NGO",
    city: "Pokhara",
    salaryMin: 35000,
    salaryMax: 45000,
    type: "mid",
    verified: false,
    tags: ["Community", "Travel"],
    exp: 2,
    teaser: "Community engagement and field data collection.",
    description:
      "Liaise with local partners, frequent travel to field sites, aggregate reports and feedback for program team.",
    applyUrl: "#",
  },
  {
    id: 4,
    title: "Frontend Developer (React)",
    company: "TechNest",
    city: "Lalitpur",
    remote: true,
    salaryMin: 60000,
    salaryMax: 90000,
    type: "mid",
    verified: true,
    tags: ["JavaScript", "React"],
    exp: 3,
    teaser: "Build and ship UI for our SaaS product.",
    description:
      "Own UI features, collaborate with backend, write tests, CI/CD. Experience with Vite, Tailwind preferred.",
    applyUrl: "#",
  },
  {
    id: 5,
    title: "Sales Trainee",
    company: "Himalayan Beverages",
    city: "Biratnagar",
    salaryMin: 20000,
    salaryMax: 28000,
    type: "intern",
    verified: false,
    tags: ["Sales", "Fresher"],
    exp: 0,
    teaser: "Entry role with mentorship and frequent market visits.",
    description:
      "Support sales team in market visits, collect competitor info, coordinate POS materials. Bike license a plus.",
    applyUrl: "#",
  },
  {
    id: 6,
    title: "IT Support Assistant",
    company: "City Hospital",
    city: "Kathmandu",
    salaryMin: 35000,
    salaryMax: 45000,
    type: "entry",
    verified: true,
    tags: ["Helpdesk", "Hardware"],
    exp: 1,
    teaser: "Provide L1 support and hardware troubleshooting.",
    description:
      "Ticket triage, device setup, network basics, CCTV maintenance. Rotational shifts including weekends.",
    applyUrl: "#",
  },
];
